package grid

import (
	"strings"
	"testing"

	tea "github.com/charmbracelet/bubbletea"

	"github.com/pgavlin/tea-grid/data"
	"github.com/pgavlin/tea-grid/filter"
	"github.com/pgavlin/tea-grid/selection"
	gridsort "github.com/pgavlin/tea-grid/sort"
)

// -----------------------------------------------------------------------
// Test helpers
// -----------------------------------------------------------------------

type TestRow struct {
	Name       string
	Department string
	Salary     float64
	Active     bool
}

func testCols() []data.ColDef[TestRow] {
	return []data.ColDef[TestRow]{
		{ColID: "Name", HeaderName: "Name", ValueGetter: func(r TestRow) any { return r.Name }, Sortable: true, Filterable: true, MinWidth: 4},
		{ColID: "Department", HeaderName: "Department", ValueGetter: func(r TestRow) any { return r.Department }, Sortable: true, Filterable: true, MinWidth: 4},
		{ColID: "Salary", HeaderName: "Salary", ValueGetter: func(r TestRow) any { return r.Salary }, Sortable: true, Filterable: true, MinWidth: 4},
		{ColID: "Active", HeaderName: "Active", ValueGetter: func(r TestRow) any { return r.Active }, Sortable: true, Filterable: true, MinWidth: 4},
	}
}

func testData() []TestRow {
	return []TestRow{
		{"Alice", "Engineering", 95000, true},
		{"Bob", "Sales", 75000, false},
		{"Carol", "Engineering", 110000, true},
		{"Dave", "Marketing", 80000, true},
		{"Eve", "Sales", 90000, false},
	}
}

func newTestGrid(opts ...Option[TestRow]) Model[TestRow] {
	defaults := []Option[TestRow]{
		WithColumns[TestRow](testCols()),
		WithRows[TestRow](testData()),
		WithFocused[TestRow](true),
		WithWidth[TestRow](80),
		WithHeight[TestRow](20),
	}
	return New(append(defaults, opts...)...)
}

// sendKey sends a single key message and returns the updated model.
func sendKey(m Model[TestRow], k tea.KeyMsg) Model[TestRow] {
	m, _ = m.Update(k)
	return m
}

// -----------------------------------------------------------------------
// 8a. Construction & Options
// -----------------------------------------------------------------------

func TestNew_Defaults(t *testing.T) {
	m := New[TestRow]()
	if m.focused {
		t.Error("expected unfocused by default")
	}
	if m.defaultRowHeight != 1 {
		t.Errorf("expected defaultRowHeight=1, got %d", m.defaultRowHeight)
	}
	if m.filterEditColIdx != -1 {
		t.Errorf("expected filterEditColIdx=-1, got %d", m.filterEditColIdx)
	}
	// After New(), recomputeDisplayRows is called which clears dirty
	if m.dirty {
		t.Error("expected dirty=false after New (recompute runs at end of New)")
	}
	if m.editable {
		t.Error("expected editable=false by default")
	}
}

func TestWithColumns(t *testing.T) {
	cols := testCols()
	m := New(WithColumns[TestRow](cols))
	if len(m.cols) != 4 {
		t.Errorf("expected 4 cols, got %d", len(m.cols))
	}
	if m.cols[0].ColID != "Name" {
		t.Errorf("expected first col 'Name', got %q", m.cols[0].ColID)
	}
}

func TestWithRows(t *testing.T) {
	m := New(WithColumns[TestRow](testCols()), WithRows[TestRow](testData()))
	if len(m.rows) != 5 {
		t.Errorf("expected 5 rows, got %d", len(m.rows))
	}
}

func TestWithRowID(t *testing.T) {
	m := New(
		WithColumns[TestRow](testCols()),
		WithRowID[TestRow](func(r TestRow) string { return "emp-" + r.Name }),
		WithRows[TestRow](testData()),
	)
	if m.rows[0].ID != "emp-Alice" {
		t.Errorf("expected 'emp-Alice', got %q", m.rows[0].ID)
	}
	if m.rows[4].ID != "emp-Eve" {
		t.Errorf("expected 'emp-Eve', got %q", m.rows[4].ID)
	}
}

func TestAutoGeneratedIDs(t *testing.T) {
	m := New(WithColumns[TestRow](testCols()), WithRows[TestRow](testData()))
	ids := make(map[string]bool)
	for _, rn := range m.rows {
		if ids[rn.ID] {
			t.Errorf("duplicate auto-generated ID: %s", rn.ID)
		}
		ids[rn.ID] = true
		if !strings.HasPrefix(rn.ID, "row-") {
			t.Errorf("expected 'row-' prefix, got %q", rn.ID)
		}
	}
}

func TestWithFocused(t *testing.T) {
	m := New(WithFocused[TestRow](true))
	if !m.focused {
		t.Error("expected focused=true")
	}
	m2 := New(WithFocused[TestRow](false))
	if m2.focused {
		t.Error("expected focused=false")
	}
}

func TestWithSelection(t *testing.T) {
	m := New(WithSelection[TestRow](selection.SelectMulti))
	if m.sel.Mode != selection.SelectMulti {
		t.Errorf("expected SelectMulti, got %d", m.sel.Mode)
	}
}

func TestWithMultiSort(t *testing.T) {
	m := New(WithMultiSort[TestRow](true))
	if !m.sortModel.MultiSort {
		t.Error("expected MultiSort=true")
	}
}

func TestWithQuickFilter(t *testing.T) {
	m := New(WithQuickFilter[TestRow](true))
	if !m.quickFilterEnabled {
		t.Error("expected quickFilterEnabled=true")
	}
}

func TestWithGrouping(t *testing.T) {
	m := New(
		WithColumns[TestRow](testCols()),
		WithRows[TestRow](testData()),
		WithGrouping[TestRow]("Department"),
	)
	if len(m.groupModel.GroupColumns) != 1 || m.groupModel.GroupColumns[0] != "Department" {
		t.Errorf("expected GroupColumns=[Department], got %v", m.groupModel.GroupColumns)
	}
}

func TestWithGroupDefaultExpanded(t *testing.T) {
	m := New(WithGroupDefaultExpanded[TestRow](2))
	if m.groupModel.DefaultExpanded != 2 {
		t.Errorf("expected DefaultExpanded=2, got %d", m.groupModel.DefaultExpanded)
	}
}

func TestWithDefaultSort(t *testing.T) {
	criteria := []gridsort.SortCriterion{
		{ColID: "Name", Direction: data.SortAsc},
	}
	m := New(
		WithColumns[TestRow](testCols()),
		WithRows[TestRow](testData()),
		WithDefaultSort[TestRow](criteria),
	)
	if len(m.sortModel.SortOrder) != 1 {
		t.Fatalf("expected 1 sort criterion, got %d", len(m.sortModel.SortOrder))
	}
	if m.sortModel.SortOrder[0].ColID != "Name" {
		t.Errorf("expected sort by Name, got %q", m.sortModel.SortOrder[0].ColID)
	}
}

func TestWithWidthHeight(t *testing.T) {
	m := New(WithWidth[TestRow](120), WithHeight[TestRow](40))
	if m.width != 120 {
		t.Errorf("expected width=120, got %d", m.width)
	}
	if m.height != 40 {
		t.Errorf("expected height=40, got %d", m.height)
	}
}

func TestWithEditable(t *testing.T) {
	m := New(WithEditable[TestRow](true))
	if !m.editable {
		t.Error("expected editable=true")
	}
}

func TestWithExternalFilter(t *testing.T) {
	fn := func(r TestRow) bool { return r.Active }
	m := New(
		WithColumns[TestRow](testCols()),
		WithRows[TestRow](testData()),
		WithExternalFilter[TestRow](fn),
	)
	if m.externalFilter == nil {
		t.Error("expected externalFilter to be set")
	}
	// Verify filtering effect: only active=true rows
	if len(m.displayRows) != 3 {
		t.Errorf("expected 3 active rows, got %d", len(m.displayRows))
	}
}

func TestWithPostSort(t *testing.T) {
	called := false
	fn := func(rows []data.RowNode[TestRow]) []data.RowNode[TestRow] {
		called = true
		return rows
	}
	m := New(
		WithColumns[TestRow](testCols()),
		WithRows[TestRow](testData()),
		WithPostSort[TestRow](fn),
	)
	_ = m
	if !called {
		t.Error("expected postSort to be called during construction")
	}
}

func TestWithRowHeight(t *testing.T) {
	m := New(
		WithRowHeight[TestRow](3),
		WithColumns[TestRow](testCols()),
		WithRows[TestRow](testData()),
	)
	for _, rn := range m.rows {
		if rn.RowHeight != 3 {
			t.Errorf("expected RowHeight=3, got %d", rn.RowHeight)
		}
	}
}

func TestWithDynamicRowHeight(t *testing.T) {
	m := New(
		WithDynamicRowHeight[TestRow](func(r TestRow) int {
			if r.Active {
				return 2
			}
			return 1
		}),
		WithColumns[TestRow](testCols()),
		WithRows[TestRow](testData()),
	)
	// Alice is active -> height 2
	if m.rows[0].RowHeight != 2 {
		t.Errorf("expected Alice RowHeight=2, got %d", m.rows[0].RowHeight)
	}
	// Bob is inactive -> height 1
	if m.rows[1].RowHeight != 1 {
		t.Errorf("expected Bob RowHeight=1, got %d", m.rows[1].RowHeight)
	}
}

func TestWithPinnedTopRows(t *testing.T) {
	m := New(
		WithColumns[TestRow](testCols()),
		WithRows[TestRow](testData()),
		WithPinnedTopRows[TestRow](func(r TestRow) bool { return r.Name == "Alice" }),
		WithWidth[TestRow](80),
		WithHeight[TestRow](20),
	)
	if len(m.pinnedTop) != 1 {
		t.Errorf("expected 1 pinned top row, got %d", len(m.pinnedTop))
	}
	if m.pinnedTop[0].Data.Name != "Alice" {
		t.Errorf("expected pinned top row to be Alice, got %s", m.pinnedTop[0].Data.Name)
	}
}

func TestWithPinnedBottomRows(t *testing.T) {
	m := New(
		WithColumns[TestRow](testCols()),
		WithRows[TestRow](testData()),
		WithPinnedBottomRows[TestRow](func(r TestRow) bool { return r.Name == "Eve" }),
		WithWidth[TestRow](80),
		WithHeight[TestRow](20),
	)
	if len(m.pinnedBot) != 1 {
		t.Errorf("expected 1 pinned bottom row, got %d", len(m.pinnedBot))
	}
}

func TestWithStaticPinnedTop(t *testing.T) {
	totals := TestRow{Name: "TOTAL", Department: "All", Salary: 450000, Active: true}
	m := New(
		WithColumns[TestRow](testCols()),
		WithRows[TestRow](testData()),
		WithStaticPinnedTop[TestRow]([]TestRow{totals}),
		WithWidth[TestRow](80),
		WithHeight[TestRow](20),
	)
	found := false
	for _, rn := range m.pinnedTop {
		if rn.Data.Name == "TOTAL" {
			found = true
		}
	}
	if !found {
		t.Error("expected TOTAL in pinned top rows")
	}
}

func TestWithStaticPinnedBottom(t *testing.T) {
	footer := TestRow{Name: "FOOTER", Department: "All", Salary: 0, Active: false}
	m := New(
		WithColumns[TestRow](testCols()),
		WithRows[TestRow](testData()),
		WithStaticPinnedBottom[TestRow]([]TestRow{footer}),
		WithWidth[TestRow](80),
		WithHeight[TestRow](20),
	)
	found := false
	for _, rn := range m.pinnedBot {
		if rn.Data.Name == "FOOTER" {
			found = true
		}
	}
	if !found {
		t.Error("expected FOOTER in pinned bottom rows")
	}
}

// -----------------------------------------------------------------------
// 8b. Data Management
// -----------------------------------------------------------------------

func TestSetRows_Rows_RoundTrip(t *testing.T) {
	m := newTestGrid()
	newData := []TestRow{
		{"Zara", "HR", 100000, true},
		{"Yuri", "IT", 105000, false},
	}
	m.SetRows(newData)
	got := m.Rows()
	if len(got) != 2 {
		t.Fatalf("expected 2 rows, got %d", len(got))
	}
	if got[0].Name != "Zara" || got[1].Name != "Yuri" {
		t.Errorf("unexpected row data: %v", got)
	}
}

func TestSetColumns_Columns_RoundTrip(t *testing.T) {
	m := newTestGrid()
	newCols := []data.ColDef[TestRow]{
		{ColID: "Name", HeaderName: "Name", ValueGetter: func(r TestRow) any { return r.Name }},
	}
	m.SetColumns(newCols)
	got := m.Columns()
	if len(got) != 1 {
		t.Fatalf("expected 1 col, got %d", len(got))
	}
	if got[0].ColID != "Name" {
		t.Errorf("expected col Name, got %q", got[0].ColID)
	}
}

func TestUpdateRow(t *testing.T) {
	// WithRowID must come before WithRows so rows get custom IDs
	m := New[TestRow](
		WithColumns[TestRow](testCols()),
		WithRowID[TestRow](func(r TestRow) string { return r.Name }),
		WithRows[TestRow](testData()),
		WithFocused[TestRow](true),
		WithWidth[TestRow](80),
		WithHeight[TestRow](20),
	)
	m.UpdateRow("Alice", TestRow{"Alice", "Management", 150000, true})
	rows := m.Rows()
	for _, r := range rows {
		if r.Name == "Alice" && r.Department != "Management" {
			t.Errorf("expected Alice in Management, got %s", r.Department)
		}
	}
}

func TestInsertRow(t *testing.T) {
	m := newTestGrid()
	before := len(m.rows)
	m.InsertRow(0, TestRow{"Zara", "HR", 100000, true})
	if len(m.rows) != before+1 {
		t.Errorf("expected %d rows, got %d", before+1, len(m.rows))
	}
	if m.rows[0].Data.Name != "Zara" {
		t.Errorf("expected Zara at index 0, got %s", m.rows[0].Data.Name)
	}
}

func TestInsertRow_AppendsBeyondLength(t *testing.T) {
	m := newTestGrid()
	m.InsertRow(999, TestRow{"Zara", "HR", 100000, true})
	last := m.rows[len(m.rows)-1]
	if last.Data.Name != "Zara" {
		t.Errorf("expected Zara appended at end, got %s", last.Data.Name)
	}
}

func TestRemoveRow(t *testing.T) {
	// WithRowID must come before WithRows so rows get custom IDs
	m := New[TestRow](
		WithColumns[TestRow](testCols()),
		WithRowID[TestRow](func(r TestRow) string { return r.Name }),
		WithRows[TestRow](testData()),
		WithFocused[TestRow](true),
		WithWidth[TestRow](80),
		WithHeight[TestRow](20),
	)
	before := len(m.rows)
	m.RemoveRow("Bob")
	if len(m.rows) != before-1 {
		t.Errorf("expected %d rows, got %d", before-1, len(m.rows))
	}
	for _, rn := range m.rows {
		if rn.Data.Name == "Bob" {
			t.Error("Bob should have been removed")
		}
	}
}

func TestDirtyFlag(t *testing.T) {
	m := newTestGrid()
	// After construction, dirty should be false
	if m.dirty {
		t.Error("expected dirty=false after full init")
	}
	m.SetRows(testData())
	// SetRows calls recomputeDisplayRows which clears dirty
	// but the flag is set then cleared; let's just verify it works without error
}

// -----------------------------------------------------------------------
// 8c. Column Sizing
// -----------------------------------------------------------------------

func TestColumnSizing_FixedWidth(t *testing.T) {
	cols := []data.ColDef[TestRow]{
		{ColID: "A", HeaderName: "A", ValueGetter: func(r TestRow) any { return r.Name }, Width: 20},
		{ColID: "B", HeaderName: "B", ValueGetter: func(r TestRow) any { return r.Department }, Width: 30},
	}
	m := newTestGrid(WithColumns[TestRow](cols))
	if m.colWidths[0] != 20 {
		t.Errorf("expected col A width=20, got %d", m.colWidths[0])
	}
	if m.colWidths[1] != 30 {
		t.Errorf("expected col B width=30, got %d", m.colWidths[1])
	}
}

func TestColumnSizing_FlexDistribution(t *testing.T) {
	cols := []data.ColDef[TestRow]{
		{ColID: "A", HeaderName: "A", ValueGetter: func(r TestRow) any { return r.Name }, Flex: 1, MinWidth: 4},
		{ColID: "B", HeaderName: "B", ValueGetter: func(r TestRow) any { return r.Department }, Flex: 1, MinWidth: 4},
	}
	s := DefaultStyles()
	s.BorderColumn = false
	m := newTestGrid(WithColumns[TestRow](cols), WithStyles[TestRow](s))
	// With no border columns and width=80, each should get ~40
	if m.colWidths[0] != 40 {
		t.Errorf("expected col A width=40, got %d", m.colWidths[0])
	}
	if m.colWidths[1] != 40 {
		t.Errorf("expected col B width=40, got %d", m.colWidths[1])
	}
}

func TestColumnSizing_MinWidthRespected(t *testing.T) {
	cols := []data.ColDef[TestRow]{
		{ColID: "A", HeaderName: "A", ValueGetter: func(r TestRow) any { return r.Name }, MinWidth: 10, Flex: 1},
		{ColID: "B", HeaderName: "B", ValueGetter: func(r TestRow) any { return r.Department }, MinWidth: 10, Flex: 1},
	}
	s := DefaultStyles()
	s.BorderColumn = false
	m := newTestGrid(WithColumns[TestRow](cols))
	if m.colWidths[0] < 10 {
		t.Errorf("expected col A width >= 10, got %d", m.colWidths[0])
	}
	if m.colWidths[1] < 10 {
		t.Errorf("expected col B width >= 10, got %d", m.colWidths[1])
	}
}

func TestColumnSizing_MaxWidthClamped(t *testing.T) {
	cols := []data.ColDef[TestRow]{
		{ColID: "A", HeaderName: "A", ValueGetter: func(r TestRow) any { return r.Name }, Flex: 1, MinWidth: 4, MaxWidth: 15},
		{ColID: "B", HeaderName: "B", ValueGetter: func(r TestRow) any { return r.Department }, Flex: 1, MinWidth: 4},
	}
	s := DefaultStyles()
	s.BorderColumn = false
	m := newTestGrid(WithColumns[TestRow](cols), WithStyles[TestRow](s))
	if m.colWidths[0] > 15 {
		t.Errorf("expected col A width <= 15, got %d", m.colWidths[0])
	}
}

func TestColumnSizing_MixedFixedAndFlex(t *testing.T) {
	cols := []data.ColDef[TestRow]{
		{ColID: "A", HeaderName: "A", ValueGetter: func(r TestRow) any { return r.Name }, Width: 20},
		{ColID: "B", HeaderName: "B", ValueGetter: func(r TestRow) any { return r.Department }, Flex: 1, MinWidth: 4},
	}
	s := DefaultStyles()
	s.BorderColumn = false
	m := newTestGrid(WithColumns[TestRow](cols), WithStyles[TestRow](s))
	if m.colWidths[0] != 20 {
		t.Errorf("expected col A width=20, got %d", m.colWidths[0])
	}
	// B gets the remaining space: 80 - 20 = 60
	if m.colWidths[1] != 60 {
		t.Errorf("expected col B width=60, got %d", m.colWidths[1])
	}
}

func TestColumnSizing_BorderColumnSubtractsSpace(t *testing.T) {
	cols := []data.ColDef[TestRow]{
		{ColID: "A", HeaderName: "A", ValueGetter: func(r TestRow) any { return r.Name }, Flex: 1, MinWidth: 4},
		{ColID: "B", HeaderName: "B", ValueGetter: func(r TestRow) any { return r.Department }, Flex: 1, MinWidth: 4},
	}
	s := DefaultStyles()
	s.BorderColumn = true
	m := newTestGrid(WithColumns[TestRow](cols), WithStyles[TestRow](s))
	// With border column, 1 separator between 2 cols -> total usable = 80-1=79
	total := m.colWidths[0] + m.colWidths[1]
	if total != 79 {
		t.Errorf("expected total col widths=79 with border, got %d", total)
	}
}

func TestColumnSizing_SingleFlexColumn(t *testing.T) {
	cols := []data.ColDef[TestRow]{
		{ColID: "A", HeaderName: "A", ValueGetter: func(r TestRow) any { return r.Name }, Flex: 1, MinWidth: 4},
	}
	s := DefaultStyles()
	s.BorderColumn = false
	m := newTestGrid(WithColumns[TestRow](cols), WithStyles[TestRow](s))
	if m.colWidths[0] != 80 {
		t.Errorf("expected single flex col width=80, got %d", m.colWidths[0])
	}
}

func TestColumnSizing_HiddenColumnsGetWidthZero(t *testing.T) {
	cols := []data.ColDef[TestRow]{
		{ColID: "A", HeaderName: "A", ValueGetter: func(r TestRow) any { return r.Name }, Flex: 1, MinWidth: 4},
		{ColID: "B", HeaderName: "B", ValueGetter: func(r TestRow) any { return r.Department }, Flex: 1, MinWidth: 4, Hide: true},
	}
	s := DefaultStyles()
	s.BorderColumn = false
	m := newTestGrid(WithColumns[TestRow](cols), WithStyles[TestRow](s))
	if m.colWidths[1] != 0 {
		t.Errorf("expected hidden col B width=0, got %d", m.colWidths[1])
	}
	// A should get all the space
	if m.colWidths[0] != 80 {
		t.Errorf("expected col A width=80, got %d", m.colWidths[0])
	}
}

// -----------------------------------------------------------------------
// 8d. Display Row Pipeline
// -----------------------------------------------------------------------

func TestDisplayRows_Unfiltered(t *testing.T) {
	m := newTestGrid()
	if len(m.displayRows) != 5 {
		t.Errorf("expected 5 display rows, got %d", len(m.displayRows))
	}
}

func TestDisplayRows_ColumnFilter(t *testing.T) {
	tf := filter.NewTextFilter()
	tf.SetText("Engineering")
	cols := testCols()
	cols[1].Filter = tf
	m := newTestGrid(WithColumns[TestRow](cols))
	// Only Engineering rows: Alice, Carol
	if len(m.displayRows) != 2 {
		t.Errorf("expected 2 rows after column filter, got %d", len(m.displayRows))
	}
}

func TestDisplayRows_QuickFilter(t *testing.T) {
	m := newTestGrid(WithQuickFilter[TestRow](true))
	m.SetQuickFilter("alice")
	if len(m.displayRows) != 1 {
		t.Errorf("expected 1 row after quick filter 'alice', got %d", len(m.displayRows))
	}
	if m.displayRows[0].Data.Name != "Alice" {
		t.Errorf("expected Alice, got %s", m.displayRows[0].Data.Name)
	}
}

func TestDisplayRows_ExternalFilter(t *testing.T) {
	m := newTestGrid(
		WithExternalFilter[TestRow](func(r TestRow) bool { return r.Active }),
	)
	// Active: Alice, Carol, Dave
	if len(m.displayRows) != 3 {
		t.Errorf("expected 3 active rows, got %d", len(m.displayRows))
	}
}

func TestDisplayRows_MultipleFiltersAND(t *testing.T) {
	tf := filter.NewTextFilter()
	tf.SetText("Engineering")
	cols := testCols()
	cols[1].Filter = tf

	m := newTestGrid(
		WithColumns[TestRow](cols),
		WithExternalFilter[TestRow](func(r TestRow) bool { return r.Salary > 100000 }),
	)
	// Engineering AND Salary > 100000: only Carol (110000)
	if len(m.displayRows) != 1 {
		t.Errorf("expected 1 row after combined filters, got %d", len(m.displayRows))
	}
	if len(m.displayRows) > 0 && m.displayRows[0].Data.Name != "Carol" {
		t.Errorf("expected Carol, got %s", m.displayRows[0].Data.Name)
	}
}

func TestDisplayRows_SortApplied(t *testing.T) {
	m := newTestGrid(
		WithDefaultSort[TestRow]([]gridsort.SortCriterion{
			{ColID: "Name", Direction: data.SortAsc},
		}),
	)
	names := make([]string, len(m.displayRows))
	for i, rn := range m.displayRows {
		names[i] = rn.Data.Name
	}
	expected := []string{"Alice", "Bob", "Carol", "Dave", "Eve"}
	for i, n := range expected {
		if names[i] != n {
			t.Errorf("position %d: expected %s, got %s", i, n, names[i])
		}
	}
}

func TestDisplayRows_SortDescending(t *testing.T) {
	m := newTestGrid(
		WithDefaultSort[TestRow]([]gridsort.SortCriterion{
			{ColID: "Name", Direction: data.SortDesc},
		}),
	)
	if m.displayRows[0].Data.Name != "Eve" {
		t.Errorf("expected Eve first in desc sort, got %s", m.displayRows[0].Data.Name)
	}
	if m.displayRows[4].Data.Name != "Alice" {
		t.Errorf("expected Alice last in desc sort, got %s", m.displayRows[4].Data.Name)
	}
}

func TestDisplayRows_PostSortHook(t *testing.T) {
	// Reverse the rows via post-sort
	m := newTestGrid(
		WithPostSort[TestRow](func(rows []data.RowNode[TestRow]) []data.RowNode[TestRow] {
			n := len(rows)
			reversed := make([]data.RowNode[TestRow], n)
			for i, rn := range rows {
				reversed[n-1-i] = rn
			}
			return reversed
		}),
	)
	// Original order is Alice,Bob,Carol,Dave,Eve; reversed is Eve,Dave,Carol,Bob,Alice
	if m.displayRows[0].Data.Name != "Eve" {
		t.Errorf("expected Eve first after post-sort reverse, got %s", m.displayRows[0].Data.Name)
	}
}

func TestDisplayRows_PinnedRowsExcludedFromSortFilter(t *testing.T) {
	m := newTestGrid(
		WithPinnedTopRows[TestRow](func(r TestRow) bool { return r.Name == "Alice" }),
		WithDefaultSort[TestRow]([]gridsort.SortCriterion{
			{ColID: "Name", Direction: data.SortDesc},
		}),
	)
	// Alice should be in pinnedTop, not in displayRows
	for _, rn := range m.displayRows {
		if rn.Data.Name == "Alice" {
			t.Error("Alice should be pinned, not in display rows")
		}
	}
	if len(m.pinnedTop) != 1 || m.pinnedTop[0].Data.Name != "Alice" {
		t.Error("expected Alice in pinned top")
	}
}

// -----------------------------------------------------------------------
// 8e. Viewport
// -----------------------------------------------------------------------

func TestViewport_EnsureRowVisible(t *testing.T) {
	v := viewport{topRow: 0, visibleRows: 5}
	v.ensureRowVisible(3)
	if v.topRow != 0 {
		t.Errorf("row 3 is visible, topRow should stay 0, got %d", v.topRow)
	}
	v.ensureRowVisible(7)
	if v.topRow != 3 {
		t.Errorf("expected topRow=3 to show row 7, got %d", v.topRow)
	}
	v.ensureRowVisible(1)
	if v.topRow != 1 {
		t.Errorf("expected topRow=1 to show row 1, got %d", v.topRow)
	}
}

func TestViewport_EnsureColVisible(t *testing.T) {
	v := viewport{leftCol: 0, visibleCols: 3}
	v.ensureColVisible(2)
	if v.leftCol != 0 {
		t.Errorf("col 2 is visible, leftCol should stay 0, got %d", v.leftCol)
	}
	v.ensureColVisible(5)
	if v.leftCol != 3 {
		t.Errorf("expected leftCol=3 to show col 5, got %d", v.leftCol)
	}
}

func TestViewport_VisibleRowRange(t *testing.T) {
	v := viewport{topRow: 2, visibleRows: 5}
	start, end := v.visibleRowRange(10)
	if start != 2 || end != 7 {
		t.Errorf("expected [2,7), got [%d,%d)", start, end)
	}
	start, end = v.visibleRowRange(4)
	if start != 2 || end != 4 {
		t.Errorf("expected [2,4) when totalRows=4, got [%d,%d)", start, end)
	}
}

func TestViewport_ScrollUpDown(t *testing.T) {
	v := viewport{topRow: 5, visibleRows: 10}
	v.scrollUp(3)
	if v.topRow != 2 {
		t.Errorf("expected topRow=2 after scrollUp(3), got %d", v.topRow)
	}
	v.scrollUp(10) // Clamp to 0
	if v.topRow != 0 {
		t.Errorf("expected topRow=0 after over-scrollUp, got %d", v.topRow)
	}

	v.topRow = 0
	v.scrollDown(5, 20)
	if v.topRow != 5 {
		t.Errorf("expected topRow=5 after scrollDown(5), got %d", v.topRow)
	}
	v.scrollDown(100, 20) // Clamp
	maxTop := 20 - 10
	if v.topRow != maxTop {
		t.Errorf("expected topRow=%d after over-scrollDown, got %d", maxTop, v.topRow)
	}
}

func TestViewport_ScrollToTopBottom(t *testing.T) {
	v := viewport{topRow: 5, visibleRows: 10}
	v.scrollToTop()
	if v.topRow != 0 {
		t.Errorf("expected topRow=0 after scrollToTop, got %d", v.topRow)
	}
	v.scrollToBottom(30)
	expected := 30 - 10
	if v.topRow != expected {
		t.Errorf("expected topRow=%d after scrollToBottom, got %d", expected, v.topRow)
	}
}

func TestViewport_ScrollToBottom_SmallList(t *testing.T) {
	v := viewport{topRow: 0, visibleRows: 10}
	v.scrollToBottom(5) // fewer rows than viewport
	if v.topRow != 0 {
		t.Errorf("expected topRow=0 when rows < viewport, got %d", v.topRow)
	}
}

// -----------------------------------------------------------------------
// 8f. Keyboard Navigation
// -----------------------------------------------------------------------

func TestNavigation_ArrowKeys(t *testing.T) {
	m := newTestGrid()
	// Initial position should be (0, 0)
	if m.focusedCell.Row != 0 || m.focusedCell.Col != 0 {
		t.Errorf("expected initial focus (0,0), got (%d,%d)", m.focusedCell.Row, m.focusedCell.Col)
	}

	// Down
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyDown})
	if m.focusedCell.Row != 1 {
		t.Errorf("expected row=1 after Down, got %d", m.focusedCell.Row)
	}

	// Right
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRight})
	if m.focusedCell.Col != 1 {
		t.Errorf("expected col=1 after Right, got %d", m.focusedCell.Col)
	}

	// Up
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyUp})
	if m.focusedCell.Row != 0 {
		t.Errorf("expected row=0 after Up, got %d", m.focusedCell.Row)
	}

	// Left
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyLeft})
	if m.focusedCell.Col != 0 {
		t.Errorf("expected col=0 after Left, got %d", m.focusedCell.Col)
	}
}

func TestNavigation_BoundsClamping(t *testing.T) {
	m := newTestGrid()
	// Move up past top -> should clamp to header (-1) then not go further
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyUp})
	if m.focusedCell.Row != -1 {
		t.Errorf("expected row=-1 (header), got %d", m.focusedCell.Row)
	}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyUp})
	if m.focusedCell.Row != -1 {
		t.Errorf("expected row=-1 after double up, got %d", m.focusedCell.Row)
	}

	// Move left past first col -> should clamp
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyLeft})
	if m.focusedCell.Col != 0 {
		t.Errorf("expected col=0 after Left at leftmost, got %d", m.focusedCell.Col)
	}

	// Go to last row, try to go past
	m.focusedCell = CellPosition{Row: len(m.displayRows) - 1, Col: 0}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyDown})
	if m.focusedCell.Row != len(m.displayRows)-1 {
		t.Errorf("expected row clamped to %d, got %d", len(m.displayRows)-1, m.focusedCell.Row)
	}
}

func TestNavigation_PageUpDown(t *testing.T) {
	m := newTestGrid()
	m.focusedCell = CellPosition{Row: 0, Col: 0}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyPgDown})
	// Page down should move by vp.visibleRows
	if m.focusedCell.Row != min(m.vp.visibleRows, len(m.displayRows)-1) {
		t.Errorf("expected row=%d after PgDown, got %d", min(m.vp.visibleRows, len(m.displayRows)-1), m.focusedCell.Row)
	}

	m.focusedCell = CellPosition{Row: 4, Col: 0}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyPgUp})
	if m.focusedCell.Row != 0 {
		t.Errorf("expected row=0 after PgUp from 4, got %d", m.focusedCell.Row)
	}
}

func TestNavigation_HomeEnd(t *testing.T) {
	m := newTestGrid()
	m.focusedCell = CellPosition{Row: 2, Col: 0}

	// Home -> row 0
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyHome})
	if m.focusedCell.Row != 0 {
		t.Errorf("expected row=0 after Home, got %d", m.focusedCell.Row)
	}

	// End -> last row
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyEnd})
	if m.focusedCell.Row != len(m.displayRows)-1 {
		t.Errorf("expected row=%d after End, got %d", len(m.displayRows)-1, m.focusedCell.Row)
	}
}

func TestNavigation_GoToHeader(t *testing.T) {
	m := newTestGrid()
	m.focusedCell = CellPosition{Row: 3, Col: 1}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'g'}})
	if m.focusedCell.Row != -1 {
		t.Errorf("expected row=-1 (header) after 'g', got %d", m.focusedCell.Row)
	}
	if m.focusedCell.Col != 1 {
		t.Errorf("expected col=1 preserved after GoToHeader, got %d", m.focusedCell.Col)
	}
}

func TestNavigation_UnfocusedIgnoresKeys(t *testing.T) {
	m := newTestGrid(WithFocused[TestRow](false))
	pos := m.focusedCell
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyDown})
	if m.focusedCell != pos {
		t.Error("expected unfocused grid to ignore key input")
	}
}

// -----------------------------------------------------------------------
// 8g. Selection Integration
// -----------------------------------------------------------------------

func TestSelection_SpaceToggles(t *testing.T) {
	m := newTestGrid(WithSelection[TestRow](selection.SelectMulti))
	m.focusedCell = CellPosition{Row: 0, Col: 0}
	rowID := m.displayRows[0].ID

	// Press space to select
	m = sendKey(m, tea.KeyMsg{Type: tea.KeySpace})
	if !m.sel.IsSelected(rowID) {
		t.Error("expected row to be selected after space")
	}

	// Press space again to deselect
	m = sendKey(m, tea.KeyMsg{Type: tea.KeySpace})
	if m.sel.IsSelected(rowID) {
		t.Error("expected row to be deselected after second space")
	}
}

func TestSelection_CtrlASelectsAll(t *testing.T) {
	m := newTestGrid(WithSelection[TestRow](selection.SelectMulti))
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyCtrlA})
	selected := m.SelectedRows()
	if len(selected) != len(m.displayRows) {
		t.Errorf("expected %d selected rows, got %d", len(m.displayRows), len(selected))
	}
}

func TestSelection_EscDeselectsAll(t *testing.T) {
	m := newTestGrid(WithSelection[TestRow](selection.SelectMulti))
	// Select all first
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyCtrlA})
	// Esc should deselect
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyEsc})
	if m.sel.Count() != 0 {
		t.Errorf("expected 0 selected after Esc, got %d", m.sel.Count())
	}
}

// -----------------------------------------------------------------------
// 8h. Sort Integration
// -----------------------------------------------------------------------

func TestSort_EnterOnHeaderTogglesSortAsc(t *testing.T) {
	m := newTestGrid()
	// Navigate to header
	m.focusedCell = CellPosition{Row: -1, Col: 0}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyEnter})
	if len(m.sortModel.SortOrder) != 1 {
		t.Fatalf("expected 1 sort criterion, got %d", len(m.sortModel.SortOrder))
	}
	if m.sortModel.SortOrder[0].Direction != data.SortAsc {
		t.Errorf("expected SortAsc, got %d", m.sortModel.SortOrder[0].Direction)
	}
}

func TestSort_EnterOnHeaderCycles(t *testing.T) {
	m := newTestGrid()
	m.focusedCell = CellPosition{Row: -1, Col: 0}

	// First enter -> asc
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyEnter})
	if m.sortModel.SortOrder[0].Direction != data.SortAsc {
		t.Errorf("expected SortAsc, got %d", m.sortModel.SortOrder[0].Direction)
	}

	// Second enter -> desc
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyEnter})
	if m.sortModel.SortOrder[0].Direction != data.SortDesc {
		t.Errorf("expected SortDesc, got %d", m.sortModel.SortOrder[0].Direction)
	}

	// Third enter -> none
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyEnter})
	if len(m.sortModel.SortOrder) != 0 {
		t.Errorf("expected 0 sort criteria after toggle to none, got %d", len(m.sortModel.SortOrder))
	}
}

func TestSort_SKeyFromAnyRow(t *testing.T) {
	m := newTestGrid()
	m.focusedCell = CellPosition{Row: 2, Col: 0} // data row

	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'s'}})
	if len(m.sortModel.SortOrder) != 1 {
		t.Fatalf("expected 1 sort criterion after 's', got %d", len(m.sortModel.SortOrder))
	}
	if m.sortModel.SortOrder[0].ColID != "Name" {
		t.Errorf("expected sort by 'Name', got %q", m.sortModel.SortOrder[0].ColID)
	}
}

func TestSort_ShiftSAddsMultiSort(t *testing.T) {
	m := newTestGrid(WithMultiSort[TestRow](true))
	m.focusedCell = CellPosition{Row: 0, Col: 0}

	// Sort by Name
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'s'}})
	// Add Department with Shift+S
	m.focusedCell.Col = 1
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'S'}})

	if len(m.sortModel.SortOrder) != 2 {
		t.Fatalf("expected 2 sort criteria, got %d", len(m.sortModel.SortOrder))
	}
	if m.sortModel.SortOrder[1].ColID != "Department" {
		t.Errorf("expected second sort by Department, got %q", m.sortModel.SortOrder[1].ColID)
	}
}

func TestSort_EmitsSortChangedMsg(t *testing.T) {
	m := newTestGrid()
	m.focusedCell = CellPosition{Row: 0, Col: 0}
	var cmd tea.Cmd
	m, cmd = m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'s'}})
	if cmd == nil {
		t.Fatal("expected a command to be emitted")
	}
	msg := cmd()
	sc, ok := msg.(SortChangedMsg)
	if !ok {
		t.Fatalf("expected SortChangedMsg, got %T", msg)
	}
	if len(sc.SortOrder) != 1 {
		t.Errorf("expected 1 criterion in SortChangedMsg, got %d", len(sc.SortOrder))
	}
}

func TestSort_UnsortableColumnIgnored(t *testing.T) {
	cols := testCols()
	cols[0].Sortable = false
	m := newTestGrid(WithColumns[TestRow](cols))
	m.focusedCell = CellPosition{Row: 0, Col: 0}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'s'}})
	if len(m.sortModel.SortOrder) != 0 {
		t.Error("expected unsortable column to be ignored")
	}
}

// -----------------------------------------------------------------------
// 8i. Filter Integration
// -----------------------------------------------------------------------

func TestQuickFilter_SlashActivates(t *testing.T) {
	m := newTestGrid(WithQuickFilter[TestRow](true))
	if m.quickFilterActive {
		t.Error("expected quick filter inactive initially")
	}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'/'}})
	if !m.quickFilterActive {
		t.Error("expected quick filter active after '/'")
	}
}

func TestQuickFilter_RunesAddToFilterText(t *testing.T) {
	m := newTestGrid(WithQuickFilter[TestRow](true))
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'/'}})
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'a'}})
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'l'}})
	if m.quickFilterText != "al" {
		t.Errorf("expected quickFilterText='al', got %q", m.quickFilterText)
	}
}

func TestQuickFilter_EnterConfirms(t *testing.T) {
	m := newTestGrid(WithQuickFilter[TestRow](true))
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'/'}})
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'a'}})
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyEnter})
	if m.quickFilterActive {
		t.Error("expected quick filter deactivated after Enter")
	}
	if m.quickFilterText != "a" {
		t.Errorf("expected quickFilterText='a' preserved after Enter, got %q", m.quickFilterText)
	}
}

func TestQuickFilter_EscClearsAndCloses(t *testing.T) {
	m := newTestGrid(WithQuickFilter[TestRow](true))
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'/'}})
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'x'}})
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyEsc})
	if m.quickFilterActive {
		t.Error("expected quick filter deactivated after Esc")
	}
	if m.quickFilterText != "" {
		t.Errorf("expected quickFilterText cleared after Esc, got %q", m.quickFilterText)
	}
}

func TestQuickFilter_FiltersResults(t *testing.T) {
	m := newTestGrid(WithQuickFilter[TestRow](true))
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'/'}})
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'e'}})
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'n'}})
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'g'}})
	// "eng" should match Engineering rows: Alice, Carol
	if len(m.displayRows) != 2 {
		t.Errorf("expected 2 rows matching 'eng', got %d", len(m.displayRows))
	}
}

func TestColumnFilter_CtrlFRequiresFilterable(t *testing.T) {
	cols := testCols()
	// No Filter set on any column
	m := newTestGrid(WithColumns[TestRow](cols))
	m.focusedCell = CellPosition{Row: 0, Col: 0}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyCtrlF})
	if m.filterEditColIdx != -1 {
		t.Error("expected column filter not to open without Filter set on column")
	}
}

func TestColumnFilter_CtrlFOpensWithFilter(t *testing.T) {
	cols := testCols()
	cols[0].Filter = filter.NewTextFilter()
	m := newTestGrid(WithColumns[TestRow](cols))
	m.focusedCell = CellPosition{Row: 0, Col: 0}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyCtrlF})
	if m.filterEditColIdx != 0 {
		t.Errorf("expected filterEditColIdx=0, got %d", m.filterEditColIdx)
	}
}

// -----------------------------------------------------------------------
// 8j. Grouping Integration
// -----------------------------------------------------------------------

func TestGrouping_GTogglesGroupColumn(t *testing.T) {
	m := newTestGrid()
	m.focusedCell = CellPosition{Row: 0, Col: 1} // Department
	var cmd tea.Cmd
	m, cmd = m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'G'}})
	if len(m.groupModel.GroupColumns) != 1 || m.groupModel.GroupColumns[0] != "Department" {
		t.Errorf("expected GroupColumns=[Department], got %v", m.groupModel.GroupColumns)
	}
	if cmd == nil {
		t.Error("expected GroupColumnsChangedMsg command")
	}

	// Toggle again to remove
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'G'}})
	if len(m.groupModel.GroupColumns) != 0 {
		t.Errorf("expected GroupColumns=[], got %v", m.groupModel.GroupColumns)
	}
}

func TestGrouping_RightExpands(t *testing.T) {
	m := newTestGrid(
		WithGrouping[TestRow]("Department"),
		WithGroupDefaultExpanded[TestRow](0),
	)
	// Find a collapsed group row
	groupIdx := -1
	for i, rn := range m.displayRows {
		if rn.IsGroup && !rn.Expanded {
			groupIdx = i
			break
		}
	}
	if groupIdx == -1 {
		t.Fatal("no collapsed group found")
	}
	m.focusedCell = CellPosition{Row: groupIdx, Col: 0}
	beforeCount := len(m.displayRows)
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRight})
	// Expanding should add child rows
	if len(m.displayRows) <= beforeCount {
		t.Error("expected more display rows after expanding group")
	}
}

func TestGrouping_LeftCollapses(t *testing.T) {
	m := newTestGrid(
		WithGrouping[TestRow]("Department"),
		WithGroupDefaultExpanded[TestRow](-1), // all expanded
	)
	// Find an expanded group row
	groupIdx := -1
	for i, rn := range m.displayRows {
		if rn.IsGroup && rn.Expanded {
			groupIdx = i
			break
		}
	}
	if groupIdx == -1 {
		t.Fatal("no expanded group found")
	}
	m.focusedCell = CellPosition{Row: groupIdx, Col: 0}
	beforeCount := len(m.displayRows)
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyLeft})
	// Collapsing should remove child rows
	if len(m.displayRows) >= beforeCount {
		t.Error("expected fewer display rows after collapsing group")
	}
}

func TestGrouping_EmitsGroupColumnsChangedMsg(t *testing.T) {
	m := newTestGrid()
	m.focusedCell = CellPosition{Row: 0, Col: 0}
	var cmd tea.Cmd
	m, cmd = m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'G'}})
	if cmd == nil {
		t.Fatal("expected a command to be emitted")
	}
	msg := cmd()
	if _, ok := msg.(GroupColumnsChangedMsg); !ok {
		t.Fatalf("expected GroupColumnsChangedMsg, got %T", msg)
	}
}

// -----------------------------------------------------------------------
// 8k. Cell Editing
// -----------------------------------------------------------------------

func TestEditing_EnterStartsEditing(t *testing.T) {
	cols := testCols()
	cols[0].Editable = true
	cols[0].ValueSetter = func(data *TestRow, val any) { data.Name = val.(string) }

	m := newTestGrid(
		WithColumns[TestRow](cols),
		WithEditable[TestRow](true),
	)
	m.focusedCell = CellPosition{Row: 0, Col: 0}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyEnter})
	if m.editState == nil {
		t.Error("expected editState to be set after Enter on editable cell")
	}
}

func TestEditing_EscCancels(t *testing.T) {
	cols := testCols()
	cols[0].Editable = true
	cols[0].ValueSetter = func(data *TestRow, val any) { data.Name = val.(string) }

	m := newTestGrid(
		WithColumns[TestRow](cols),
		WithEditable[TestRow](true),
	)
	m.focusedCell = CellPosition{Row: 0, Col: 0}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyEnter})
	if m.editState == nil {
		t.Fatal("expected editing to start")
	}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyEsc})
	if m.editState != nil {
		t.Error("expected editState=nil after Esc")
	}
}

func TestEditing_NonEditableCellDoesNotStart(t *testing.T) {
	cols := testCols()
	// col[0] is NOT editable

	m := newTestGrid(
		WithColumns[TestRow](cols),
		WithEditable[TestRow](true),
	)
	m.focusedCell = CellPosition{Row: 0, Col: 0}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyEnter})
	if m.editState != nil {
		t.Error("expected no editing on non-editable cell")
	}
}

func TestEditing_RequiresWithEditable(t *testing.T) {
	cols := testCols()
	cols[0].Editable = true

	m := newTestGrid(
		WithColumns[TestRow](cols),
		// WithEditable NOT set (default false)
	)
	m.focusedCell = CellPosition{Row: 0, Col: 0}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyEnter})
	if m.editState != nil {
		t.Error("expected no editing when grid editable=false")
	}
}

// -----------------------------------------------------------------------
// 8l. Rendering
// -----------------------------------------------------------------------

func TestRender_NonEmpty(t *testing.T) {
	m := newTestGrid()
	output := m.View()
	if len(output) == 0 {
		t.Error("expected non-empty View() output")
	}
}

func TestRender_EmptyWithZeroDimensions(t *testing.T) {
	m := New[TestRow](
		WithColumns[TestRow](testCols()),
		WithRows[TestRow](testData()),
	)
	// No width/height set, both 0
	output := m.View()
	if output != "" {
		t.Error("expected empty View() with zero dimensions")
	}
}

func TestRender_HeaderRendered(t *testing.T) {
	m := newTestGrid()
	output := m.View()
	if !strings.Contains(output, "Name") {
		t.Error("expected header 'Name' in output")
	}
	if !strings.Contains(output, "Department") {
		t.Error("expected header 'Department' in output")
	}
	if !strings.Contains(output, "Salary") {
		t.Error("expected header 'Salary' in output")
	}
}

func TestRender_DataRowsRendered(t *testing.T) {
	m := newTestGrid()
	output := m.View()
	if !strings.Contains(output, "Alice") {
		t.Error("expected 'Alice' in output")
	}
	if !strings.Contains(output, "Bob") {
		t.Error("expected 'Bob' in output")
	}
}

func TestRender_SortIndicators(t *testing.T) {
	m := newTestGrid(
		WithDefaultSort[TestRow]([]gridsort.SortCriterion{
			{ColID: "Name", Direction: data.SortAsc},
		}),
	)
	output := m.View()
	if !strings.Contains(output, m.styles.SortAsc) {
		t.Errorf("expected sort asc indicator %q in output", m.styles.SortAsc)
	}

	// Change to desc
	m.SetSort([]gridsort.SortCriterion{
		{ColID: "Name", Direction: data.SortDesc},
	})
	output = m.View()
	if !strings.Contains(output, m.styles.SortDesc) {
		t.Errorf("expected sort desc indicator %q in output", m.styles.SortDesc)
	}
}

func TestRender_GroupRow(t *testing.T) {
	m := newTestGrid(
		WithGrouping[TestRow]("Department"),
		WithGroupDefaultExpanded[TestRow](-1),
	)
	output := m.View()
	// Should contain the group expanded indicator and group key
	if !strings.Contains(output, "Engineering") {
		t.Error("expected 'Engineering' group label in output")
	}
	if !strings.Contains(output, m.styles.GroupExpanded) {
		t.Errorf("expected group expanded indicator %q in output", m.styles.GroupExpanded)
	}
}

func TestRender_QuickFilterBarShownWhenActive(t *testing.T) {
	m := newTestGrid(WithQuickFilter[TestRow](true))
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'/'}})
	output := m.View()
	if !strings.Contains(output, "Filter:") {
		t.Error("expected 'Filter:' label in output when quick filter active")
	}
}

// -----------------------------------------------------------------------
// 8m. Public API
// -----------------------------------------------------------------------

func TestPublicAPI_FocusBlur(t *testing.T) {
	m := newTestGrid()
	m.Blur()
	if m.Focused() {
		t.Error("expected unfocused after Blur")
	}
	m.Focus()
	if !m.Focused() {
		t.Error("expected focused after Focus")
	}
}

func TestPublicAPI_SetFocusedCell_FocusedCell(t *testing.T) {
	m := newTestGrid()
	m.SetFocusedCell(CellPosition{Row: 2, Col: 3})
	pos := m.FocusedCell()
	if pos.Row != 2 || pos.Col != 3 {
		t.Errorf("expected (2,3), got (%d,%d)", pos.Row, pos.Col)
	}
}

func TestPublicAPI_SelectDeselectRow(t *testing.T) {
	m := newTestGrid(WithSelection[TestRow](selection.SelectMulti))
	id := m.rows[0].ID
	m.SelectRow(id)
	if !m.IsSelected(id) {
		t.Error("expected row to be selected")
	}
	m.DeselectRow(id)
	if m.IsSelected(id) {
		t.Error("expected row to be deselected")
	}
}

func TestPublicAPI_SelectAll_DeselectAll(t *testing.T) {
	m := newTestGrid(WithSelection[TestRow](selection.SelectMulti))
	m.SelectAll()
	if len(m.SelectedRows()) != 5 {
		t.Errorf("expected 5 selected rows, got %d", len(m.SelectedRows()))
	}
	m.DeselectAll()
	if len(m.SelectedRows()) != 0 {
		t.Errorf("expected 0 selected rows, got %d", len(m.SelectedRows()))
	}
}

func TestPublicAPI_SelectedRows(t *testing.T) {
	// WithRowID must come before WithRows so rows get custom IDs
	m := New[TestRow](
		WithColumns[TestRow](testCols()),
		WithSelection[TestRow](selection.SelectMulti),
		WithRowID[TestRow](func(r TestRow) string { return r.Name }),
		WithRows[TestRow](testData()),
		WithFocused[TestRow](true),
		WithWidth[TestRow](80),
		WithHeight[TestRow](20),
	)
	m.SelectRow("Alice")
	m.SelectRow("Carol")
	selected := m.SelectedRows()
	if len(selected) != 2 {
		t.Fatalf("expected 2 selected, got %d", len(selected))
	}
	names := make(map[string]bool)
	for _, r := range selected {
		names[r.Name] = true
	}
	if !names["Alice"] || !names["Carol"] {
		t.Errorf("expected Alice and Carol selected, got %v", selected)
	}
}

func TestPublicAPI_IsSelected(t *testing.T) {
	m := newTestGrid(WithSelection[TestRow](selection.SelectMulti))
	id := m.rows[1].ID
	if m.IsSelected(id) {
		t.Error("expected not selected initially")
	}
	m.SelectRow(id)
	if !m.IsSelected(id) {
		t.Error("expected selected after SelectRow")
	}
}

func TestPublicAPI_SetSort_SortOrder(t *testing.T) {
	m := newTestGrid()
	criteria := []gridsort.SortCriterion{
		{ColID: "Salary", Direction: data.SortDesc},
	}
	m.SetSort(criteria)
	got := m.SortOrder()
	if len(got) != 1 || got[0].ColID != "Salary" || got[0].Direction != data.SortDesc {
		t.Errorf("unexpected sort order: %v", got)
	}
	// Verify rows sorted by salary desc
	if m.displayRows[0].Data.Salary != 110000 {
		t.Errorf("expected highest salary first, got %v", m.displayRows[0].Data.Salary)
	}
}

func TestPublicAPI_SetQuickFilter(t *testing.T) {
	m := newTestGrid()
	m.SetQuickFilter("bob")
	if len(m.displayRows) != 1 {
		t.Errorf("expected 1 row for 'bob', got %d", len(m.displayRows))
	}
}

func TestPublicAPI_SetColumnFilter(t *testing.T) {
	cols := testCols()
	cols[0].Filter = filter.NewTextFilter()
	m := newTestGrid(WithColumns[TestRow](cols))

	tf := filter.NewTextFilter()
	tf.SetText("Carol")
	m.SetColumnFilter("Name", tf)
	if len(m.displayRows) != 1 {
		t.Errorf("expected 1 row for Name='Carol', got %d", len(m.displayRows))
	}
}

func TestPublicAPI_ClearFilters(t *testing.T) {
	cols := testCols()
	cols[0].Filter = filter.NewTextFilter()
	m := newTestGrid(WithColumns[TestRow](cols))

	tf := filter.NewTextFilter()
	tf.SetText("Carol")
	m.SetColumnFilter("Name", tf)
	m.SetQuickFilter("xyz")
	m.ClearFilters()
	if len(m.displayRows) != 5 {
		t.Errorf("expected 5 rows after ClearFilters, got %d", len(m.displayRows))
	}
}

func TestPublicAPI_ExpandCollapseGroup(t *testing.T) {
	m := newTestGrid(
		WithGrouping[TestRow]("Department"),
		WithGroupDefaultExpanded[TestRow](0), // all collapsed
	)
	// Find a group key
	groupKey := ""
	for _, rn := range m.displayRows {
		if rn.IsGroup {
			groupKey = rn.GroupKey
			break
		}
	}
	if groupKey == "" {
		t.Fatal("no group row found")
	}

	beforeCount := len(m.displayRows)
	m.ExpandGroup(groupKey)
	if len(m.displayRows) <= beforeCount {
		t.Error("expected more rows after ExpandGroup")
	}

	expandedCount := len(m.displayRows)
	m.CollapseGroup(groupKey)
	if len(m.displayRows) >= expandedCount {
		t.Error("expected fewer rows after CollapseGroup")
	}
}

func TestPublicAPI_ExpandAll_CollapseAll(t *testing.T) {
	m := newTestGrid(
		WithGrouping[TestRow]("Department"),
		WithGroupDefaultExpanded[TestRow](0), // all collapsed
	)
	collapsedCount := len(m.displayRows)
	m.ExpandAll()
	if len(m.displayRows) <= collapsedCount {
		t.Error("expected more rows after ExpandAll")
	}
	m.CollapseAll()
	if len(m.displayRows) != collapsedCount {
		t.Errorf("expected same count as initial collapsed after CollapseAll, got %d vs %d",
			len(m.displayRows), collapsedCount)
	}
}

func TestPublicAPI_ScrollToRow(t *testing.T) {
	m := newTestGrid()
	m.ScrollToRow(4)
	// Should ensure row 4 is visible
	start, end := m.vp.visibleRowRange(len(m.displayRows))
	if !(4 >= start && 4 < end) {
		t.Errorf("row 4 not in visible range [%d,%d)", start, end)
	}
}

func TestPublicAPI_ScrollToTop(t *testing.T) {
	m := newTestGrid()
	m.vp.topRow = 10
	m.ScrollToTop()
	if m.vp.topRow != 0 {
		t.Errorf("expected topRow=0 after ScrollToTop, got %d", m.vp.topRow)
	}
}

func TestPublicAPI_ScrollToBottom(t *testing.T) {
	m := newTestGrid()
	m.ScrollToBottom()
	expected := len(m.displayRows) - m.vp.visibleRows
	if expected < 0 {
		expected = 0
	}
	if m.vp.topRow != expected {
		t.Errorf("expected topRow=%d after ScrollToBottom, got %d", expected, m.vp.topRow)
	}
}

func TestPublicAPI_PinUnpinColumn(t *testing.T) {
	m := newTestGrid()
	m.PinColumn("Name", data.PinLeft)
	if m.cols[0].Pinned != data.PinLeft {
		t.Errorf("expected Name pinned left, got %d", m.cols[0].Pinned)
	}
	m.UnpinColumn("Name")
	if m.cols[0].Pinned != data.PinNone {
		t.Errorf("expected Name unpinned, got %d", m.cols[0].Pinned)
	}
}

func TestPublicAPI_PinUnpinRow(t *testing.T) {
	// WithRowID must come before WithRows so rows get custom IDs
	m := New[TestRow](
		WithColumns[TestRow](testCols()),
		WithRowID[TestRow](func(r TestRow) string { return r.Name }),
		WithRows[TestRow](testData()),
		WithFocused[TestRow](true),
		WithWidth[TestRow](80),
		WithHeight[TestRow](20),
	)
	m.PinRow("Alice", data.PinTop)
	// Recomputation should move Alice to pinnedTop
	found := false
	for _, rn := range m.pinnedTop {
		if rn.Data.Name == "Alice" {
			found = true
		}
	}
	if !found {
		t.Error("expected Alice in pinned top after PinRow")
	}

	m.UnpinRow("Alice")
	// Alice should be back in display rows
	foundInPinned := false
	for _, rn := range m.pinnedTop {
		if rn.Data.Name == "Alice" {
			foundInPinned = true
		}
	}
	if foundInPinned {
		t.Error("expected Alice removed from pinned top after UnpinRow")
	}
}

func TestPublicAPI_HelpView(t *testing.T) {
	m := newTestGrid()
	help := m.HelpView()
	if len(help) == 0 {
		t.Error("expected non-empty HelpView")
	}
}

func TestPublicAPI_WidthHeight(t *testing.T) {
	m := newTestGrid()
	if m.Width() != 80 {
		t.Errorf("expected Width()=80, got %d", m.Width())
	}
	if m.Height() != 20 {
		t.Errorf("expected Height()=20, got %d", m.Height())
	}
	m.SetWidth(100)
	if m.Width() != 100 {
		t.Errorf("expected Width()=100, got %d", m.Width())
	}
	m.SetHeight(30)
	if m.Height() != 30 {
		t.Errorf("expected Height()=30, got %d", m.Height())
	}
}

// -----------------------------------------------------------------------
// 8n. defaultCompare
// -----------------------------------------------------------------------

func TestDefaultCompare_Strings(t *testing.T) {
	tests := []struct {
		a, b any
		want int
	}{
		{"apple", "banana", -1},
		{"banana", "apple", 1},
		{"same", "same", 0},
		{"", "a", -1},
	}
	for _, tt := range tests {
		got := defaultCompare(tt.a, tt.b)
		if got != tt.want {
			t.Errorf("defaultCompare(%q, %q) = %d, want %d", tt.a, tt.b, got, tt.want)
		}
	}
}

func TestDefaultCompare_Ints(t *testing.T) {
	tests := []struct {
		a, b any
		want int
	}{
		{1, 2, -1},
		{5, 3, 1},
		{7, 7, 0},
		{-1, 0, -1},
	}
	for _, tt := range tests {
		got := defaultCompare(tt.a, tt.b)
		if got != tt.want {
			t.Errorf("defaultCompare(%v, %v) = %d, want %d", tt.a, tt.b, got, tt.want)
		}
	}
}

func TestDefaultCompare_Int64(t *testing.T) {
	tests := []struct {
		a, b any
		want int
	}{
		{int64(100), int64(200), -1},
		{int64(200), int64(100), 1},
		{int64(42), int64(42), 0},
	}
	for _, tt := range tests {
		got := defaultCompare(tt.a, tt.b)
		if got != tt.want {
			t.Errorf("defaultCompare(%v, %v) = %d, want %d", tt.a, tt.b, got, tt.want)
		}
	}
}

func TestDefaultCompare_Float64(t *testing.T) {
	tests := []struct {
		a, b any
		want int
	}{
		{1.5, 2.5, -1},
		{3.14, 2.71, 1},
		{9.99, 9.99, 0},
	}
	for _, tt := range tests {
		got := defaultCompare(tt.a, tt.b)
		if got != tt.want {
			t.Errorf("defaultCompare(%v, %v) = %d, want %d", tt.a, tt.b, got, tt.want)
		}
	}
}

func TestDefaultCompare_Bools(t *testing.T) {
	tests := []struct {
		a, b any
		want int
	}{
		{false, true, -1},
		{true, false, 1},
		{true, true, 0},
		{false, false, 0},
	}
	for _, tt := range tests {
		got := defaultCompare(tt.a, tt.b)
		if got != tt.want {
			t.Errorf("defaultCompare(%v, %v) = %d, want %d", tt.a, tt.b, got, tt.want)
		}
	}
}

func TestDefaultCompare_UnknownTypesFallback(t *testing.T) {
	type Custom struct{ V int }
	a := Custom{1}
	b := Custom{2}
	// Fallback to fmt.Sprint comparison
	got := defaultCompare(a, b)
	// {1} vs {2} -> string comparison
	if got == 0 && a != b {
		t.Error("expected non-zero comparison for different custom types")
	}
}

func TestDefaultCompare_MixedTypesFallback(t *testing.T) {
	// int vs string -> fallback to string comparison
	got := defaultCompare(42, "hello")
	// "42" vs "hello" -> "42" < "hello"
	if got >= 0 {
		t.Errorf("expected defaultCompare(42, 'hello') < 0, got %d", got)
	}
}

// -----------------------------------------------------------------------
// Additional edge case tests
// -----------------------------------------------------------------------

func TestInit_ReturnsNil(t *testing.T) {
	m := newTestGrid()
	cmd := m.Init()
	if cmd != nil {
		t.Error("expected Init() to return nil")
	}
}

func TestSetWidthHeight_UpdatesDimensions(t *testing.T) {
	m := newTestGrid()
	m.SetWidth(120)
	m.SetHeight(40)
	if m.width != 120 {
		t.Errorf("expected width=120, got %d", m.width)
	}
	if m.height != 40 {
		t.Errorf("expected height=40, got %d", m.height)
	}
}

func TestQuickFilter_DisabledIgnoresSlash(t *testing.T) {
	m := newTestGrid() // quickFilterEnabled is false by default
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'/'}})
	if m.quickFilterActive {
		t.Error("expected quick filter not to activate when disabled")
	}
}

func TestQuickFilter_BackspaceRemovesChar(t *testing.T) {
	m := newTestGrid(WithQuickFilter[TestRow](true))
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'/'}})
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'a'}})
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'b'}})
	if m.quickFilterText != "ab" {
		t.Fatalf("expected 'ab', got %q", m.quickFilterText)
	}
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyBackspace})
	if m.quickFilterText != "a" {
		t.Errorf("expected 'a' after backspace, got %q", m.quickFilterText)
	}
}

func TestSort_NumericSort(t *testing.T) {
	m := newTestGrid(
		WithDefaultSort[TestRow]([]gridsort.SortCriterion{
			{ColID: "Salary", Direction: data.SortAsc},
		}),
	)
	for i := 1; i < len(m.displayRows); i++ {
		prev := m.displayRows[i-1].Data.Salary
		curr := m.displayRows[i].Data.Salary
		if prev > curr {
			t.Errorf("rows not sorted by salary asc: %v > %v at index %d", prev, curr, i)
		}
	}
}

func TestRowIndices_AreUpdated(t *testing.T) {
	m := newTestGrid()
	for i, rn := range m.displayRows {
		if rn.RowIndex != i {
			t.Errorf("expected RowIndex=%d, got %d for row %s", i, rn.RowIndex, rn.Data.Name)
		}
	}
}

func TestShortHelp_ReturnsBindings(t *testing.T) {
	m := newTestGrid()
	bindings := m.ShortHelp()
	if len(bindings) == 0 {
		t.Error("expected non-empty short help bindings")
	}
}

func TestFullHelp_ReturnsBindingGroups(t *testing.T) {
	m := newTestGrid()
	groups := m.FullHelp()
	if len(groups) == 0 {
		t.Error("expected non-empty full help binding groups")
	}
}

func TestQuitKey(t *testing.T) {
	m := newTestGrid()
	_, cmd := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'q'}})
	if cmd == nil {
		t.Error("expected quit command from 'q' key")
	}
}

func TestHelpToggle(t *testing.T) {
	m := newTestGrid()
	before := m.Help.ShowAll
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'?'}})
	if m.Help.ShowAll == before {
		t.Error("expected Help.ShowAll to toggle")
	}
}

func TestSelectedRowNodes(t *testing.T) {
	// WithRowID must come before WithRows so rows get custom IDs
	m := New[TestRow](
		WithColumns[TestRow](testCols()),
		WithSelection[TestRow](selection.SelectMulti),
		WithRowID[TestRow](func(r TestRow) string { return r.Name }),
		WithRows[TestRow](testData()),
		WithFocused[TestRow](true),
		WithWidth[TestRow](80),
		WithHeight[TestRow](20),
	)
	m.SelectRow("Alice")
	nodes := m.SelectedRowNodes()
	if len(nodes) != 1 {
		t.Fatalf("expected 1 selected node, got %d", len(nodes))
	}
	if nodes[0].Data.Name != "Alice" {
		t.Errorf("expected Alice, got %s", nodes[0].Data.Name)
	}
}

// -----------------------------------------------------------------------
// Horizontal Scrolling Tests
// -----------------------------------------------------------------------

func TestHorizontalScroll_ColumnsExceedViewport(t *testing.T) {
	// Create columns whose MinWidths total > viewport width (80)
	cols := []data.ColDef[TestRow]{
		{ColID: "A", HeaderName: "A", ValueGetter: func(r TestRow) any { return r.Name }, MinWidth: 30},
		{ColID: "B", HeaderName: "B", ValueGetter: func(r TestRow) any { return r.Department }, MinWidth: 30},
		{ColID: "C", HeaderName: "C", ValueGetter: func(r TestRow) any { return r.Salary }, MinWidth: 30},
	}
	s := DefaultStyles()
	s.BorderColumn = false
	m := newTestGrid(WithColumns[TestRow](cols), WithStyles[TestRow](s))

	// Not all columns should be visible at once
	if m.vp.visibleCols >= 3 {
		t.Errorf("expected visibleCols < 3 (cols exceed viewport), got %d", m.vp.visibleCols)
	}

	// All columns should be reachable via navigation
	m.focusedCell = CellPosition{Row: 0, Col: 0}
	// Navigate right to column B (index 1)
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRight})
	if m.focusedCell.Col != 1 {
		t.Errorf("expected col=1 after Right, got %d", m.focusedCell.Col)
	}
	// Navigate right to column C (index 2)
	m = sendKey(m, tea.KeyMsg{Type: tea.KeyRight})
	if m.focusedCell.Col != 2 {
		t.Errorf("expected col=2 after second Right, got %d", m.focusedCell.Col)
	}
}

func TestHorizontalScroll_LeftColUpdatesVisibleCols(t *testing.T) {
	// Columns with varying widths; total exceeds viewport width
	cols := []data.ColDef[TestRow]{
		{ColID: "A", HeaderName: "A", ValueGetter: func(r TestRow) any { return r.Name }, Width: 25},
		{ColID: "B", HeaderName: "B", ValueGetter: func(r TestRow) any { return r.Department }, Width: 25},
		{ColID: "C", HeaderName: "C", ValueGetter: func(r TestRow) any { return r.Salary }, Width: 25},
		{ColID: "D", HeaderName: "D", ValueGetter: func(r TestRow) any { return r.Active }, Width: 25},
	}
	s := DefaultStyles()
	s.BorderColumn = false
	m := newTestGrid(WithColumns[TestRow](cols), WithStyles[TestRow](s))

	// Width=80, 4 cols * 25 = 100 > 80, so not all visible
	initialVisible := m.vp.visibleCols
	if initialVisible >= 4 {
		t.Fatalf("expected < 4 visible cols, got %d", initialVisible)
	}

	// Navigate right until leftCol changes
	m.focusedCell = CellPosition{Row: 0, Col: 0}
	for i := 0; i < 3; i++ {
		m = sendKey(m, tea.KeyMsg{Type: tea.KeyRight})
	}

	// After scrolling right, visibleCols should still be correct
	// (recomputed from the new leftCol position)
	if m.vp.visibleCols < 1 {
		t.Error("expected at least 1 visible col after scrolling")
	}
}

func TestHorizontalScroll_VaryingWidths(t *testing.T) {
	// First column is very wide, rest are narrow
	cols := []data.ColDef[TestRow]{
		{ColID: "A", HeaderName: "A", ValueGetter: func(r TestRow) any { return r.Name }, Width: 50},
		{ColID: "B", HeaderName: "B", ValueGetter: func(r TestRow) any { return r.Department }, Width: 10},
		{ColID: "C", HeaderName: "C", ValueGetter: func(r TestRow) any { return r.Salary }, Width: 10},
		{ColID: "D", HeaderName: "D", ValueGetter: func(r TestRow) any { return r.Active }, Width: 10},
	}
	s := DefaultStyles()
	s.BorderColumn = false
	m := newTestGrid(WithColumns[TestRow](cols), WithStyles[TestRow](s))

	// At leftCol=0, the wide column takes most space
	visibleAt0 := m.vp.visibleCols

	// Navigate right past the wide column
	m.focusedCell = CellPosition{Row: 0, Col: 0}
	for i := 0; i < 3; i++ {
		m = sendKey(m, tea.KeyMsg{Type: tea.KeyRight})
	}

	// After scrolling past the wide column, more narrow columns should fit
	if m.vp.leftCol > 0 && m.vp.visibleCols <= visibleAt0 {
		// When we've scrolled past the wide column, more columns should fit
		// (unless we haven't scrolled enough for leftCol to change)
		if m.vp.leftCol > 0 {
			t.Logf("leftCol=%d, visibleCols at 0=%d, visibleCols now=%d",
				m.vp.leftCol, visibleAt0, m.vp.visibleCols)
		}
	}

	// Key invariant: we should be able to see the focused column
	_, center, _ := m.visibleColIndices()
	visibleCenter := m.visibleCenterCols(center)
	found := false
	for _, idx := range visibleCenter {
		if idx == m.focusedCell.Col {
			found = true
			break
		}
	}
	if !found {
		t.Error("focused column should always be in the visible center columns")
	}
}

func TestUpdateVisibleColCount_CountsFromLeftCol(t *testing.T) {
	// Set up a grid with fixed-width columns that exceed viewport
	cols := []data.ColDef[TestRow]{
		{ColID: "A", HeaderName: "A", ValueGetter: func(r TestRow) any { return r.Name }, Width: 30},
		{ColID: "B", HeaderName: "B", ValueGetter: func(r TestRow) any { return r.Department }, Width: 30},
		{ColID: "C", HeaderName: "C", ValueGetter: func(r TestRow) any { return r.Salary }, Width: 30},
	}
	s := DefaultStyles()
	s.BorderColumn = false
	m := newTestGrid(WithColumns[TestRow](cols), WithStyles[TestRow](s))

	// At leftCol=0: 80/30 = 2 cols fit
	m.vp.leftCol = 0
	m.updateVisibleColCount()
	visibleAt0 := m.vp.visibleCols
	if visibleAt0 != 2 {
		t.Errorf("expected 2 visible cols at leftCol=0, got %d", visibleAt0)
	}

	// At leftCol=1: starting from col B, still 2 cols of 30px each fit in 80px
	m.vp.leftCol = 1
	m.updateVisibleColCount()
	visibleAt1 := m.vp.visibleCols
	if visibleAt1 != 2 {
		t.Errorf("expected 2 visible cols at leftCol=1, got %d", visibleAt1)
	}

	// At leftCol=2: only 1 col left (col C)
	m.vp.leftCol = 2
	m.updateVisibleColCount()
	visibleAt2 := m.vp.visibleCols
	if visibleAt2 != 1 {
		t.Errorf("expected 1 visible col at leftCol=2, got %d", visibleAt2)
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
